# Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                    index=['cobra', 'viper', 'sidewinder'],
                    columns=['max_speed', 'shield'])
df

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [5]:
df.loc[df['shield'] == 8]

max_speed  shield
sidewinder          7       8

In [6]:
df.loc[lambda df: df['shield'] == 8]

max_speed  shield
sidewinder          7       8

# Multi-indexing

In [1]:
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]

In [3]:
tuples = list(zip(*arrays))
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [4]:
print('hello')

hello


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
obj = TfidfVectorizer()
corpus = ['This is sample document.', 'another random document.', 'third sample document text']
X = obj.fit_transform(corpus)
print(X)

  (0, 7)	0.58448290102
  (0, 2)	0.58448290102
  (0, 4)	0.444514311537
  (0, 1)	0.345205016865
  (1, 1)	0.385371627466
  (1, 0)	0.652490884513
  (1, 3)	0.652490884513
  (2, 4)	0.444514311537
  (2, 1)	0.345205016865
  (2, 6)	0.58448290102
  (2, 5)	0.58448290102


In [9]:
X

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

https://towardsdatascience.com/machine-learning-nlp-text-classification-using-scikit-learn-python-and-nltk-c52b92a7c73a

In [1]:
'hell'

'hell'

In [ ]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(data_home = '..\\temp_1\\20news-bydate-train' , subset='train', shuffle=True)
#type(twenty_train)
#help(fetch_20newsgroups)

In [13]:
twenty_train.target_names #prints all the categories
print("\n".join(twenty_train.data[0].split("\n")[:3])) #prints first line of the first data file
twenty_train.data[0]

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu


"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape
X_train_counts

<11314x130107 sparse matrix of type '<class 'numpy.int64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [14]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(11314, 130107)

In [19]:
from scipy.sparse import csr_matrix
A = csr_matrix([[1,2,0],[0,0,3],[4,0,5]])
print(A.nonzero()) 


(array([0, 0, 1, 2, 2], dtype=int32), array([0, 1, 2, 0, 2], dtype=int32))


In [20]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [21]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()),
                    ('clf', MultinomialNB()),
                    ])
text_clf = text_clf.fit(twenty_train.data, twenty_train.target)

In [29]:
import numpy as np
twenty_test = fetch_20newsgroups(subset='test', shuffle=True)
predicted = text_clf.predict_proba(twenty_test.data)
predicted.shape
#np.mean(predicted == twenty_test.target)

(7532, 20)

In [31]:
predicted[0, :]

array([ 0.02414228,  0.03726827,  0.02685029,  0.05604283,  0.04462883,
        0.02457658,  0.02098929,  0.17286286,  0.05315145,  0.06561341,
        0.0888776 ,  0.03809724,  0.07839158,  0.04259472,  0.0547993 ,
        0.04997763,  0.05124369,  0.02804679,  0.02134034,  0.020505  ])

In [28]:
help(text_clf.predict_proba)

Help on function predict_proba in module sklearn.pipeline:

predict_proba(self, X)
    Apply transforms, and predict_proba of the final estimator
    
    Parameters
    ----------
    X : iterable
        Data to predict on. Must fulfill input requirements of first step
        of the pipeline.
    
    Returns
    -------
    y_proba : array-like, shape = [n_samples, n_classes]



In [34]:
text_clf.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
clf.class_count_

array([ 480.,  584.,  591.,  590.,  578.,  593.,  585.,  594.,  598.,
        597.,  600.,  595.,  591.,  594.,  593.,  599.,  546.,  564.,
        465.,  377.])

In [39]:
twenty_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [44]:
print(zip(text_clf.classes_, text_clf.predict_proba(twenty_test.data)[0]))

In [27]:
names = list('abcd')
vals  = reversed(list(range(len(names))))
zipped = zip(names, vals)
#list(zipped)

In [28]:
sorted(zipped, key=lambda x: x[1])

[('d', 0), ('c', 1), ('b', 2), ('a', 3)]

In [30]:
list(zipped)

[]

In [31]:
x = [1,2,3,4]
y = [7,8,3,2]
z = ['a','b','c','d']

zip_1 = zip(x,y)
list(zip_1)

[(1, 7), (2, 8), (3, 3), (4, 2)]

In [32]:
list(zip_1)

[]

In [33]:
name_list = [(1,"juca"),(22,"james"),(53,"xuxa"),(44,"delicia")]

[i for i, v in enumerate(name_list) if v[0] == 53]

[2]

In [34]:
#[x[0] for x in a]

[x[0] for x in name_list].index(53)

2

In [43]:
list_1 = ['a','b','c','d']
list_2 = [[0.1 , 0.2 , 0.3, 0.4], [0.5,0.6,0.7,0.8] , [0.1 , 0.2 , 0.3, 0.4] , [0.1 , 0.2 , 0.3, 0.4] , [0.1 , 0.2 , 0.3, 0.4]]
list_3 = []
for list_2_2 in list_2:
    list_3.append(list(zip(list_1 , list_2_2)))
list_3

[[('a', 0.1), ('b', 0.2), ('c', 0.3), ('d', 0.4)],
 [('a', 0.5), ('b', 0.6), ('c', 0.7), ('d', 0.8)],
 [('a', 0.1), ('b', 0.2), ('c', 0.3), ('d', 0.4)],
 [('a', 0.1), ('b', 0.2), ('c', 0.3), ('d', 0.4)],
 [('a', 0.1), ('b', 0.2), ('c', 0.3), ('d', 0.4)]]

In [ ]:
my_list = [('a', [0.1, 0.2, 0.3, 0.4]), ('b', [0.5, 0.6, 0.7, 0.8])]
sorted(zipped, key=lambda x: x[1], reverse=True )

In [41]:
label_prob = []
l = [[('1234' , 0.2) , ('5678' , 0.3) , ('9012' , 0.5)] , [('1234' , 0.3) , ('5678' , 0.5) , ('9012' , 0.2)] ]
for l_1 in l : 
    label_prob.append(sorted(l_1, key=lambda x: x[1], reverse=True ))
label_prob

[[('9012', 0.5), ('5678', 0.3), ('1234', 0.2)],
 [('5678', 0.5), ('1234', 0.3), ('9012', 0.2)]]